# --- ОСНОВНАЯ БАЗА ДАННЫХ (PRIMARY) ---
spring.datasource.primary.jdbc-url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/printing_shop}
spring.datasource.primary.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.primary.password=${SPRING_DATASOURCE_PASSWORD:00000000}
spring.datasource.primary.driver-class-name=org.postgresql.Driver

# --- АРХИВНАЯ БАЗА ДАННЫХ (ARCHIVE) ---
spring.datasource.archive.jdbc-url=${SPRING_DATASOURCE_ARCHIVE_URL:jdbc:postgresql://127.0.0.1:5432/printing_archive}
spring.datasource.archive.username=${SPRING_DATASOURCE_ARCHIVE_USERNAME:postgres}
spring.datasource.archive.password=${SPRING_DATASOURCE_ARCHIVE_PASSWORD:00000000}
spring.datasource.archive.driver-class-name=org.postgresql.Driver

# --- НАСТРОЙКИ JPA / HIBERNATE --- update
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- ЗАГРУЗКА ФАЙЛОВ ---
spring.servlet.multipart.max-file-size=16MB
spring.servlet.multipart.max-request-size=16MB