# ==========================================
# ????????? ??????????? ? POSTGRESQL
# ==========================================

# URL ????? ???? ??????. 
# localhost:5432 - ??????????? ????? ? ???? Postgres. 
# printing_db - ???????? ???? ?????? (?? ????? ??????? ? pgAdmin ????? ???????? ???????!)
spring.datasource.url=jdbc:postgresql://localhost:5432/printing_shop

# ??? ???????????? ???? (?? ????????? ? Postgres ??? postgres)
spring.datasource.username=postgres

# ??????, ??????? ?? ????????? ??? ????????? PostgreSQL ?? ??? ?????????
spring.datasource.password=00000000

# ??????? ??? ?????? ? PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# ????????? JPA / HIBERNATE
# ==========================================

# ?????????????? ???????? ?????? ?? ?????? Java-??????? (@Entity).
# 'update' ????????? ????????? ? ?????????? ????? ???????/??????? ??? ???????? ?????? ??????.
# ??? ????????????? ??????? ??? ????? ??????? ?????.
spring.jpa.hibernate.ddl-auto=update

# ?????????? SQL-??????? ? ??????? IDE (????? ???????? ??? ???????, ?? ???????, ??? Spring ?????? INSERT ? SELECT)
spring.jpa.show-sql=true

# ????????????? SQL-??????? ? ???????, ????? ??? ???? ?????????
spring.jpa.properties.hibernate.format_sql=true

# ???????? ???????? SQL ????????? ??? PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect